# Copyright 2017 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by chef-codegen and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

gauth_credential 'mycred' do
  action :serviceaccount
  path '/home/nelsonjr/my_account.json'
  scopes [
    'https://www.googleapis.com/auth/ndev.clouddns.readwrite'
  ]
end

gcompute_network 'resource(network,0)' do
  action :create
  project 'test project#0 data'
  credential 'mycred'
  description 'test description#0 data'
  gateway_ipv4 'test gateway_ipv4#0 data'
  ipv4_range 'test ipv4_range#0 data'
  n_label 'test name#0 data'
  auto_create_subnetworks true
end

gcompute_network 'resource(network,1)' do
  action :create
  project 'test project#1 data'
  credential 'mycred'
  description 'test description#1 data'
  gateway_ipv4 'test gateway_ipv4#1 data'
  ipv4_range 'test ipv4_range#1 data'
  n_label 'test name#1 data'
  auto_create_subnetworks false
end

gcompute_network 'resource(network,2)' do
  action :create
  project 'test project#2 data'
  credential 'mycred'
  description 'test description#2 data'
  gateway_ipv4 'test gateway_ipv4#2 data'
  ipv4_range 'test ipv4_range#2 data'
  n_label 'test name#2 data'
  auto_create_subnetworks true
end

gcompute_route 'title0' do
  action :create
  project 'test project#0 data'
  credential 'mycred'
  dest_range 'test dest_range#0 data'
  network 'resource(network,0)'
  priority 1_108_918_677
  tags %w[mm nn oo pp]
  next_hop_gateway 'test next_hop_gateway#0 data'
  next_hop_instance 'test next_hop_instance#0 data'
  next_hop_ip 'test next_hop_ip#0 data'
  next_hop_vpn_tunnel 'test next_hop_vpn_tunnel#0 data'
  r_label 'test name#0 data'
end

gcompute_route 'title1' do
  action :create
  project 'test project#1 data'
  credential 'mycred'
  dest_range 'test dest_range#1 data'
  network 'resource(network,1)'
  priority 2_217_837_354
  tags %w[bb cc dd]
  next_hop_gateway 'test next_hop_gateway#1 data'
  next_hop_instance 'test next_hop_instance#1 data'
  next_hop_ip 'test next_hop_ip#1 data'
  next_hop_vpn_tunnel 'test next_hop_vpn_tunnel#1 data'
  r_label 'test name#1 data'
end

gcompute_route 'title2' do
  action :create
  project 'test project#2 data'
  credential 'mycred'
  dest_range 'test dest_range#2 data'
  network 'resource(network,2)'
  priority 3_326_756_031
  tags %w[qq rr]
  next_hop_gateway 'test next_hop_gateway#2 data'
  next_hop_instance 'test next_hop_instance#2 data'
  next_hop_ip 'test next_hop_ip#2 data'
  next_hop_vpn_tunnel 'test next_hop_vpn_tunnel#2 data'
  r_label 'test name#2 data'
end
